[project]
name = "sdetails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
sdetails = "sdetails.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
